template = "https://github.com/giellalt/template-lang-und"
rev_id = 298
template_sha = "4822abccfb9b3ce82bf2876217cde02b5f647d14"

[replacements]
__GLOTTOLOG_ID__ = "dogr1252"
__REPO__ = "lang-dgr"
__UND2C__ = "dgr"
__UNDEFINED__ = "Dogrib"
__UND__ = "dgr"
